# Generated by Django 4.2.2 on 2023-08-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderplaced_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='quantity',
        ),
    ]
