# Generated by Django 4.2.2 on 2023-08-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_orderplaced_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
